---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoinjectsecrets
  labels:
    app: demoinjectsecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoinjectsecrets
  template:
    metadata:
      labels:
        app: demoinjectsecrets
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "jenkins"
        vault.hashicorp.com/agent-inject-secret-gpg-private-key.b64: "secret/data/jenkins/gpg"
        vault.hashicorp.com/agent-inject-template-gpg-private-key.b64: |
          {{- with secret "secret/data/jenkins/gpg" -}}
          {{ .Data.data.privatekey }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-gpg-public-key.b64: "secret/data/jenkins/gpg"
        vault.hashicorp.com/agent-inject-template-gpg-public-key.b64: |
          {{- with secret "secret/data/jenkins/gpg" -}}
          {{ .Data.data.publickey }}
          {{- end -}}
    spec:
      serviceAccountName: buildagent
      containers:
      - name: buildah
        image: docker.local/davidmilet/cicd:buildah-with-nexus-ingress-cert
        imagePullPolicy: Always
        tty: true
        #command:
        #- cat
