apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  namespace: vault-project
spec:
  storageClassName: vault-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/vault-volume/
