FROM quay.io/buildah/stable
COPY infrastructure/nexus/tls.crt /etc/pki/ca-trust/source/anchors/nexus-ingress.crt
RUN update-ca-trust && \
dnf makecache && \
dnf install -y podman skopeo gnupg2 && \
dnf clean all
