FROM quay.io/buildah/stable
COPY infrastructure/tls/tls.crt /etc/pki/ca-trust/source/anchors/minikube-ingress.crt

RUN update-ca-trust && \
dnf makecache && \
dnf install -y podman skopeo gnupg2 && \
dnf clean all && \
mkdir -p /app/sigstore && \
mkdir -p /vault

COPY images/buildah/app  /app
COPY images/buildah/etc /etc
#COPY vault /vault
RUN chmod a+x /app/*.sh
CMD ["/app/buildah-image-entrypoint.sh"]
