apiVersion: v1
kind: PersistentVolume
metadata:
  name: conjur-pv
  namespace: conjur-project
spec:
  storageClassName: conjur-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/conjur-volume/
